spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coucommercedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: app
    password: app-secret

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

server:
  port: 8080

jwt:
  secret: rYc3wyeAhG3i5pHYlMKLy23xAT7wxlxWEgRIw891deXjDobnv+ayPwS5qlxtjcb1M5Eb9T3WKfAD3Rn/eV5tBA==
  refresh-token-expiration-time: 360000
  access-token-expiration-time: 3600000
