spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/coucommercedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:2000ms}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:360000}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:3600000}
